version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/tmp
    steps:
      - checkout
      - run: npm --prefix app install
      - run: npm --prefix app test

