version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/tmp
    steps:
      - checkout
      - run: npm --prefix app install
        run: npm run lint

build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/tmp
    steps:
      - checkout
      - run: npm --prefix server install
      - run: npm run lint